set nocompatible       " Make Vim more useful
set t_Co=256

syntax on
set guifont=Monaco:h14
colorscheme molokai

" Use the OS clipboard by default (on versions compiled with `+clipboard`)
set clipboard=unnamed
" Allow cursor keys in insert mode
set esckeys

" This makes vim act like all other editors, buffers can
" exist in the background without being in a window.
" http://items.sjbach.com/319/configuring-vim-right
set hidden

" ====== General Options ======

set history=1000

set number             " Show line numbers
" set relativenumber     " Show relative line numbers
set cursorline         " Highlight cursor line
set showcmd            " Show incomplete commands in status bar
set showmode           " Show current mode in status bar
set visualbell         " No sounds
set autoread           " Reload files modified outside vim
set laststatus=2       " Always show status line
set showmatch          " Show matching brackets
set matchtime=2        " Highlight matching brackets 0.2 seconds
set matchpairs+=<:>    " Especially for HTML tags

set ruler

" ====== Tabline / Toolbar options ======
" let g:airline#extensions#tabline#left_sep = ' '
" let g:airline#extensions#tabline#left_alt_sep = '|'
" let g:airline#extensions#tabline#enabled = 1

" ====== File specific options ======

filetype on
filetype plugin on
filetype indent on

" ====== Indentation ======

set autoindent
set smartindent
" set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab


" ====== Folding ======

set foldmethod=indent    " Fold based on indent
set foldnestmax=3        " deepest fold level set to 3
set nofoldenable         " Folding is deactivated by default


" ====== Scrolling ======

set scrolloff=5
set sidescrolloff=15
set sidescroll=1


" ====== Code Completion ======

set wildmode=list:longest
set wildmenu
set wildignore=*.o,*.obj
set wildignore+=*DS_Store*
set wildignore+=*.gem
set wildignore+=*.png,*.jpg,*.jpeg,*.gif


" ====== Swap / Temp files ======

set noswapfile
set nobackup
set nowb


" Allow backspace in insert mode
set backspace=indent,eol,start


" ====== Plugins handled by vundle ======

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle, required
Plugin 'gmarik/vundle'

" For nice toolbar
Plugin 'bling/vim-airline'

" Ctrl-P fuzzy file search plugin
Plugin 'kien/ctrlp.vim'

" Coffeescript syntax highlighting
Plugin 'kchmck/vim-coffee-script'

" Install common Ruby Support
Plugin 'vim-ruby/vim-ruby'

" C / C++ related plugins
Plugin 'vim-scripts/a.vim'

let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra'

" ====== Some key mappings ======

" short cuts for moving line / selection up or down in every mode
nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==
inoremap <C-j> <Esc>:m .+1<CR>==gi
inoremap <C-k> <Esc>:m .-2<CR>==gi
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv

